include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    curly_braces_in_flow_control_structures: ignore
    avoid_print: ignore
    sort_child_properties_last: ignore
  plugins:
    - custom_lint

linter:
  rules:
    prefer_const_constructors: true
    prefer_interpolation_to_compose_strings: true
    prefer_if_null_operators: true