name: sugar_tracker
description: A new Flutter project.

publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  archive: ^3.6.1
  file_picker: ^5.5.0
  firebase_core: ^3.1.1
  firebase_storage: ^12.1.0
  flutter:
    sdk: flutter
  flutter_file_dialog: ^3.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.5.1
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.0.1
  path: ^1.8.3
  path_provider: ^2.0.15
  riverpod_annotation: ^2.3.5
  settings_ui: ^2.0.2
  share_plus: ^7.0.2
  shared_preferences: ^2.2.0
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  sqflite_common_ffi: ^2.3.3+1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/food/
    - assets/images/food_category/